In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
data = pd.read_csv("/content/student_data.csv")
print(data.head())

# Separate features (X) and target (y)
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Convert categorical columns in X to numerical using one-hot encoding
X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Make predictions on the test set
pred = model.predict(X_test)

acc = accuracy_score(y_test, pred)
print("Accuracy:", acc)
cm = confusion_matrix(y_test, pred)
print(cm)

  school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]
Accuracy: 0.3924050632911392
[[4 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 2 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [2 0 0 0 2 0 2 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 1 5 2 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 3 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 2 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 3 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 1 3 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 4 6 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 2 0 0 0]
 